# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(922, 620)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setStyleSheet("#widget{\n"
"    border-radius:22px;\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.0284091, x2:0, y2:1, stop:0 rgba(152, 98, 255, 255), stop:1 rgba(199, 255, 255, 255));\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_1 = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_1.sizePolicy().hasHeightForWidth())
        self.frame_1.setSizePolicy(sizePolicy)
        self.frame_1.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_1.setMouseTracking(True)
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_1)
        self.pushButton_12.setMinimumSize(QtCore.QSize(21, 21))
        self.pushButton_12.setMaximumSize(QtCore.QSize(21, 21))
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"    border-image: url(:/icons/arrow-left.svg);\n"
"}\n"
"")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_4.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_1)
        self.pushButton_13.setMinimumSize(QtCore.QSize(21, 21))
        self.pushButton_13.setMaximumSize(QtCore.QSize(21, 21))
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"    border-image: url(:/icons/arrow-right.svg);\n"
"}")
        self.pushButton_13.setText("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_4.addWidget(self.pushButton_13)
        spacerItem = QtWidgets.QSpacerItem(395, 16, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_8 = QtWidgets.QLabel(self.frame_1)
        self.label_8.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        spacerItem1 = QtWidgets.QSpacerItem(395, 16, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_1)
        self.pushButton_2.setMinimumSize(QtCore.QSize(16, 16))
        self.pushButton_2.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border-image: url(:/icons/bug.svg);\n"
"}\n"
"")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_1)
        self.pushButton_11.setMinimumSize(QtCore.QSize(16, 16))
        self.pushButton_11.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"    border-image: url(:/icons/pin-angle.svg);\n"
"}\n"
"")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_4.addWidget(self.pushButton_11)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(16, 16))
        self.pushButton_7.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    background-color: rgb(231, 193, 75);\n"
"    border:1px solid rgb(166, 151, 66);\n"
"    border-radius:8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(124, 111, 38);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(231, 193, 75);\n"
"}\n"
"")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_4.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(16, 16))
        self.pushButton_8.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"    background-color: rgb(35, 158, 33);\n"
"    border:1px solid rgb(25, 87, 16);\n"
"    border-radius:8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(15, 118, 13);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(35, 158, 33);\n"
"}\n"
"")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_4.addWidget(self.pushButton_8)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(16, 16))
        self.pushButton_6.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    background-color: rgb(240, 108, 96);\n"
"    border:1px solid rgba(113, 17, 15,50);\n"
"    border-radius:8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(139, 29, 31);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(232, 59, 35);\n"
"}\n"
"")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_4.addWidget(self.pushButton_6)
        self.verticalLayout_6.addWidget(self.frame_1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setStyleSheet("#frame_2{\n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border-bottom-right-radius: 22px;\n"
"    border-bottom-left-radius: 22px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(11, -1, 11, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_8.setContentsMargins(10, 5, 10, 10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.comboBox = QtWidgets.QComboBox(self.frame_4)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox.setStyleSheet("QComboBox{\n"
"    padding: 5px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox::drop-down {\n"
"    padding: 3px;\n"
"    border-radius: 5px;\n"
"    width: 15px;\n"
"    border: none;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    image: url(:/icons/caret-down-fill.svg);\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"    border-radius: 15px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(141, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9.setMinimumSize(QtCore.QSize(200, 200))
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"    border-radius:50px;\n"
"    background-color: qlineargradient(spread:reflect, x1:0.576, y1:0.506, x2:0.283, y2:0.772727, stop:0.381443 rgba(26, 55, 255, 20), stop:1 rgba(255, 255, 255, 100));\n"
"    opacity:0.6;\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:reflect, x1:0.576, y1:0.506, x2:0.283, y2:0.772727, stop:0.381443 rgba(26, 55, 255, 20), stop:1 rgba(255, 255, 255, 150));\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: qlineargradient(spread:reflect, x1:0.576, y1:0.506, x2:0.283, y2:0.772727, stop:0.381443 rgba(20, 50, 255, 20), stop:1 rgba(240, 240, 240, 150));\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_6.addWidget(self.pushButton_9)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame)
        self.pushButton_10.setMinimumSize(QtCore.QSize(200, 200))
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"    border-radius:50px;\n"
"    background-color: qlineargradient(spread:reflect, x1:0.576, y1:0.506, x2:0.283, y2:0.772727, stop:0.381443 rgba(26, 55, 255, 20), stop:1 rgba(255, 255, 255, 100));\n"
"    opacity:0.6;\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:reflect, x1:0.576, y1:0.506, x2:0.283, y2:0.772727, stop:0.381443 rgba(26, 55, 255, 20), stop:1 rgba(255, 255, 255, 150));\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: qlineargradient(spread:reflect, x1:0.576, y1:0.506, x2:0.283, y2:0.772727, stop:0.381443 rgba(20, 50, 255, 20), stop:1 rgba(240, 240, 240, 150));\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_6.addWidget(self.pushButton_10)
        self.horizontalLayout.addLayout(self.horizontalLayout_6)
        spacerItem5 = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 8)
        self.horizontalLayout_13.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"#frame_3{\n"
"    border-bottom-right-radius: 22px;\n"
"    border-bottom-left-radius: 22px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(400, 80))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setMinimumSize(QtCore.QSize(110, 55))
        self.frame_6.setMaximumSize(QtCore.QSize(110, 55))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_6)
        self.label.setMinimumSize(QtCore.QSize(76, 30))
        self.label.setMaximumSize(QtCore.QSize(76, 30))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.line_2 = QtWidgets.QFrame(self.frame_6)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.frame_13 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton = QtWidgets.QPushButton(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(115, 55))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border-radius:20px;\n"
"    background-color: qlineargradient(spread:reflect, x1:0.576, y1:0.506, x2:0.283, y2:0.772727, stop:0.381443 rgba(26, 55, 255, 20), stop:1 rgba(255, 255, 255, 100));\n"
"    opacity:0.6;\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:reflect, x1:0.576, y1:0.506, x2:0.283, y2:0.772727, stop:0.381443 rgba(26, 55, 255, 20), stop:1 rgba(255, 255, 255, 150));\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: qlineargradient(spread:reflect, x1:0.576, y1:0.506, x2:0.283, y2:0.772727, stop:0.381443 rgba(20, 50, 255, 20), stop:1 rgba(240, 240, 240, 150));\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(115, 55))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    border-radius:20px;\n"
"    background-color: qlineargradient(spread:reflect, x1:0.576, y1:0.506, x2:0.283, y2:0.772727, stop:0.381443 rgba(26, 55, 255, 20), stop:1 rgba(255, 255, 255, 100));\n"
"    opacity:0.6;\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:reflect, x1:0.576, y1:0.506, x2:0.283, y2:0.772727, stop:0.381443 rgba(26, 55, 255, 20), stop:1 rgba(255, 255, 255, 150));\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: qlineargradient(spread:reflect, x1:0.576, y1:0.506, x2:0.283, y2:0.772727, stop:0.381443 rgba(20, 50, 255, 20), stop:1 rgba(240, 240, 240, 150));\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.horizontalLayout_3.addWidget(self.frame_13)
        self.line = QtWidgets.QFrame(self.frame_5)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.horizontalLayout_3.setStretch(2, 2)
        self.verticalLayout_7.addWidget(self.frame_5)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_10 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_18 = QtWidgets.QFrame(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_18.sizePolicy().hasHeightForWidth())
        self.frame_18.setSizePolicy(sizePolicy)
        self.frame_18.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_18.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_12 = QtWidgets.QLabel(self.frame_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(76, 30))
        self.label_12.setMaximumSize(QtCore.QSize(76, 30))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_18)
        self.textBrowser.setMinimumSize(QtCore.QSize(70, 35))
        self.textBrowser.setMaximumSize(QtCore.QSize(80, 35))
        self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_10.addWidget(self.textBrowser)
        self.verticalLayout_2.addWidget(self.frame_18)
        self.frame_15 = QtWidgets.QFrame(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_9 = QtWidgets.QLabel(self.frame_15)
        self.label_9.setMinimumSize(QtCore.QSize(76, 30))
        self.label_9.setMaximumSize(QtCore.QSize(76, 30))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_14.addWidget(self.label_9)
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_4.sizePolicy().hasHeightForWidth())
        self.textBrowser_4.setSizePolicy(sizePolicy)
        self.textBrowser_4.setMinimumSize(QtCore.QSize(70, 35))
        self.textBrowser_4.setMaximumSize(QtCore.QSize(80, 35))
        self.textBrowser_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.horizontalLayout_14.addWidget(self.textBrowser_4)
        self.verticalLayout_2.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_16.sizePolicy().hasHeightForWidth())
        self.frame_16.setSizePolicy(sizePolicy)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_10 = QtWidgets.QLabel(self.frame_16)
        self.label_10.setMinimumSize(QtCore.QSize(76, 30))
        self.label_10.setMaximumSize(QtCore.QSize(76, 30))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_15.addWidget(self.label_10)
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.frame_16)
        self.textBrowser_5.setMinimumSize(QtCore.QSize(70, 35))
        self.textBrowser_5.setMaximumSize(QtCore.QSize(80, 35))
        self.textBrowser_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.horizontalLayout_15.addWidget(self.textBrowser_5)
        self.verticalLayout_2.addWidget(self.frame_16)
        self.horizontalLayout_18.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_14 = QtWidgets.QFrame(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.frame_14)
        self.label_6.setMinimumSize(QtCore.QSize(76, 30))
        self.label_6.setMaximumSize(QtCore.QSize(76, 30))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.frame_14)
        self.textBrowser_3.setMinimumSize(QtCore.QSize(70, 35))
        self.textBrowser_3.setMaximumSize(QtCore.QSize(80, 35))
        self.textBrowser_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.horizontalLayout_11.addWidget(self.textBrowser_3)
        self.verticalLayout_3.addWidget(self.frame_14)
        self.frame_17 = QtWidgets.QFrame(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_17.sizePolicy().hasHeightForWidth())
        self.frame_17.setSizePolicy(sizePolicy)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_11 = QtWidgets.QLabel(self.frame_17)
        self.label_11.setMinimumSize(QtCore.QSize(76, 30))
        self.label_11.setMaximumSize(QtCore.QSize(76, 30))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_17.addWidget(self.label_11)
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.frame_17)
        self.textBrowser_6.setMinimumSize(QtCore.QSize(70, 35))
        self.textBrowser_6.setMaximumSize(QtCore.QSize(80, 35))
        self.textBrowser_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.horizontalLayout_17.addWidget(self.textBrowser_6)
        self.verticalLayout_3.addWidget(self.frame_17)
        self.horizontalLayout_18.addLayout(self.verticalLayout_3)
        self.horizontalLayout_18.setStretch(0, 1)
        self.horizontalLayout_18.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.frame_10)
        self.verticalLayout_7.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_11 = QtWidgets.QFrame(self.frame_8)
        self.frame_11.setMinimumSize(QtCore.QSize(110, 55))
        self.frame_11.setMaximumSize(QtCore.QSize(110, 55))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.frame_11)
        self.label_3.setMinimumSize(QtCore.QSize(76, 30))
        self.label_3.setMaximumSize(QtCore.QSize(76, 30))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.line_4 = QtWidgets.QFrame(self.frame_11)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_9.addWidget(self.line_4)
        self.horizontalLayout_12.addWidget(self.frame_11)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame_8)
        self.textBrowser_2.setMaximumSize(QtCore.QSize(500, 100))
        self.textBrowser_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.horizontalLayout_12.addWidget(self.textBrowser_2)
        self.verticalLayout_7.addWidget(self.frame_8)
        self.horizontalLayout_13.addWidget(self.frame_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.verticalLayout_5.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_6.clicked.connect(MainWindow.close)
        self.pushButton_7.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">成绩分析工具</span></p></body></html>"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>调试模式</p></body></html>"))
        self.pushButton_11.setToolTip(_translate("MainWindow", "<html><head/><body><p>窗口始终置顶</p></body></html>"))
        self.pushButton_7.setToolTip(_translate("MainWindow", "<html><head/><body><p>缩小到任务栏</p></body></html>"))
        self.pushButton_8.setToolTip(_translate("MainWindow", "<html><head/><body><p>全屏显示</p></body></html>"))
        self.pushButton_6.setToolTip(_translate("MainWindow", "<html><head/><body><p>关闭</p></body></html>"))
        self.frame_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>窗口始终置顶</p></body></html>"))
        self.comboBox.setItemText(0, _translate("MainWindow", "请选择试卷类型"))
        self.comboBox.setItemText(1, _translate("MainWindow", "四级"))
        self.comboBox.setItemText(2, _translate("MainWindow", "六级"))
        self.comboBox.setItemText(3, _translate("MainWindow", "考研"))
        self.comboBox.setItemText(4, _translate("MainWindow", "托福"))
        self.comboBox.setItemText(5, _translate("MainWindow", "GRE"))
        self.comboBox.setItemText(6, _translate("MainWindow", "雅思"))
        self.pushButton_9.setText(_translate("MainWindow", "考试练习"))
        self.pushButton_10.setText(_translate("MainWindow", "成绩分析"))
        self.label.setText(_translate("MainWindow", "AI作文打分"))
        self.pushButton.setText(_translate("MainWindow", "编辑文本"))
        self.pushButton_3.setText(_translate("MainWindow", "选择图片"))
        self.label_12.setText(_translate("MainWindow", "总分"))
        self.label_9.setText(_translate("MainWindow", "词汇得分"))
        self.label_10.setText(_translate("MainWindow", "逻辑得分"))
        self.label_6.setText(_translate("MainWindow", "语法得分"))
        self.label_11.setText(_translate("MainWindow", "内容得分"))
        self.label_3.setText(_translate("MainWindow", "点评结果"))
import icons_rc
